# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68858ab3977aaef4c56e61d26eedc766c6fc49327b9519e0b86ba61ba40dcc6078cb331cc779a771517c781831d1de6c7dae63b6dcfee5e1fc5a92f0d32922b

test:
  secret_key_base: 86ea8165b40c21d1091048d971bf5a31726d50484d4f334fef671eb0a411c8d78d2ef9144ab6833f249af7314e25e72052487ff728d0fea31cf614af1c4ead47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>